### ISSUE TITLE
[v2] connecting to desktop app: not connected

### ISSUE THREAD

**Issue by marcus-crane** [jtzero/asdf-1password-cli#3]
Hi there,

I'm filing this issue just for anyone else who might come here having issues with v2 of the 1password cli.

It seems that part of the CLI is only entitled, via codesigning, to operate out of `/usr/local/bin/op`: https://1password.community/discussion/comment/632995/#Comment_632995

As a result, this plugin may cause issues for users if they invoke `op` via the shim that lives in `$HOME/.asdf/shims`:

```shell
 which op
/Users/marcus/.asdf/shims/op
 op signin
[ERROR] 2022/05/16 21:14:10 connecting to desktop app: not connected
 /usr/local/bin/op signin
 Select account  [Use arrows to move, type to filter]
> Marcus Crane (my.1password.com)
```

The symptom you'll see is that `op` can never seem to connect to 1password 8 (the desktop application)

**Comment by jtzero** [comment]
Sorry on the delay on that, however according to farther down in that thread https://1password.community/discussion/comment/657013/#Comment_657013

> On Linux, it is important that the CLI is owned by a group named onepassword-cli and has the setgid bit set. Check the [Requirements tab for Linux](https://1password.community/home/leaving?allowTrusted=1&target=https%3A%2F%2Fdeveloper.1password.com%2Fdocs%2Fcli%2Fget-started%23requirements) in the Getting Started guide how to do that (you can ignore the part about the /usr/local/bin/op).

the most recent merge should fix that up
