### ISSUE TITLE
Feature asdf-1Password-cli on the 1Password Developer showcase :)

### ISSUE THREAD

**Issue by techcraver** [jtzero/asdf-1password-cli#7]
👋
I'm Jason, a Developer Evangelist at 1Password. On our [Developer Portal](https://developer.1password.com/), we have a place where we [showcase community projects](https://developer.1password.com/community) that are built with or on 1Password's Developer Tools.

We'd love to feature your repo! Would you be up for [submitting](https://github.com/1Password/developer-community-projects/pulls) a PR?

**Comment by jtzero** [comment]
Hi @techcraver ,
  While that is exciting, I have not spent enough time or attention on thi lately, and think at this time it wouldn't be a good idea

**Comment by KyThuat1-TLTVietNam** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.
raphaelcarlosr, @mattbmoorin, @crocla, @xasopheno, @philipcolejohnson, @SwJay, @leonardorb, @qinhanlei, @es1o, @jinsley8, @dapurv5, @pablofuenca, @skzhou, @patriciomacadden, @vinaymavi, @mehdidc, @skidrow91, @flrngel, @gh12128, @laurenceyoon
